server:
  http:
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Root@123456@tcp(192.168.0.110:3307)/goods?parseTime=true
  redis:
    addr: 192.168.0.110:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
