server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Root@123456@tcp(192.168.2.27:3307)/order?parseTime=true
  redis:
    addr: 192.168.2.27:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
