server:
  http:
    addr: 0.0.0.0:8001
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Root@123456@tcp(192.168.0.106:3307)/order?parseTime=true
  redis:
    addr: 192.168.0.106:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    addr: 127.0.0.1:9092